CRITICAL - 2022-10-25 04:08:07 --> The framework needs the following extension(s) installed and loaded: intl.
in SYSTEMPATH\CodeIgniter.php on line 219.
 1 SYSTEMPATH\CodeIgniter.php(219): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
 2 SYSTEMPATH\CodeIgniter.php(177): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
 3 FCPATH\index.php(55): CodeIgniter\CodeIgniter->initialize()
CRITICAL - 2022-10-25 04:08:39 --> The framework needs the following extension(s) installed and loaded: intl.
in SYSTEMPATH\CodeIgniter.php on line 219.
 1 SYSTEMPATH\CodeIgniter.php(219): CodeIgniter\Exceptions\FrameworkException::forMissingExtension('intl')
 2 SYSTEMPATH\CodeIgniter.php(177): CodeIgniter\CodeIgniter->resolvePlatformExtensions()
 3 FCPATH\index.php(55): CodeIgniter\CodeIgniter->initialize()
ERROR - 2022-10-25 21:34:23 --> Error: Class "Time" not found in C:\xampp\htdocs\pulpox11\app\Controllers\API\v1\Usuarios.php:64
Stack trace:
#0 C:\xampp\htdocs\pulpox11\system\CodeIgniter.php(902): App\Controllers\API\v1\Usuarios->registro()
#1 C:\xampp\htdocs\pulpox11\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\v1\Usuarios))
#2 C:\xampp\htdocs\pulpox11\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\pulpox11\public\index.php(67): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2022-10-25 21:39:44 --> Encrypter needs a starter key.
in SYSTEMPATH\Encryption\Encryption.php on line 124.
 1 SYSTEMPATH\Encryption\Encryption.php(124): CodeIgniter\Encryption\Exceptions\EncryptionException::forNeedsStarterKey()
 2 SYSTEMPATH\Config\Services.php(240): CodeIgniter\Encryption\Encryption->initialize(Object(Config\Encryption))
 3 SYSTEMPATH\Config\BaseService.php(253): CodeIgniter\Config\Services::encrypter()
 4 APPPATH\Controllers\API\v1\Usuarios.php(61): CodeIgniter\Config\BaseService::__callStatic('encrypter', [])
 5 SYSTEMPATH\CodeIgniter.php(902): App\Controllers\API\v1\Usuarios->registro()
 6 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\v1\Usuarios))
 7 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-10-25 22:29:34 --> Email: sendWithSmtp throwed ErrorException: fsockopen(): php_network_getaddresses: getaddrinfo for www.doinmobiliaria.comm failed: Host desconocido.  in C:\xampp\htdocs\pulpox11\system\Email\Email.php:1863
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'fsockopen(): ph...', 'C:\\xampp\\htdocs...', 1863)
#1 C:\xampp\htdocs\pulpox11\system\Email\Email.php(1863): fsockopen('tls://www.doinm...', 465, NULL, NULL, 60)
#2 C:\xampp\htdocs\pulpox11\system\Email\Email.php(1777): CodeIgniter\Email\Email->SMTPConnect()
#3 C:\xampp\htdocs\pulpox11\system\Email\Email.php(1662): CodeIgniter\Email\Email->sendWithSmtp()
#4 C:\xampp\htdocs\pulpox11\system\Email\Email.php(1560): CodeIgniter\Email\Email->spoolEmail()
#5 C:\xampp\htdocs\pulpox11\app\Controllers\API\v1\Usuarios.php(85): CodeIgniter\Email\Email->send()
#6 C:\xampp\htdocs\pulpox11\system\CodeIgniter.php(902): App\Controllers\API\v1\Usuarios->registro()
#7 C:\xampp\htdocs\pulpox11\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\v1\Usuarios))
#8 C:\xampp\htdocs\pulpox11\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\pulpox11\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2022-10-25 22:29:34 --> Email: Unable to send email using SMTP. Your server might not be configured to send mail using this method.
ERROR - 2022-10-25 22:29:34 --> 
ERROR - 2022-10-25 22:29:34 --> c.dzul@hotmail.com - Unable to send email using SMTP. Your server might not be configured to send mail using this method.<br /><pre>Date: Tue, 25 Oct 2022 22:29:34 -0600
From: &quot;Pulpox&quot; &lt;antonio.dzul@doinmobiliaria.com&gt;
Return-Path: &lt;antonio.dzul@doinmobiliaria.com&gt;
To: c.dzul@hotmail.com
Subject: =?UTF-8?Q?Para=20confirmar=20tu=20correo=20(&lt;b&gt;c.dzul@hotmail.com&lt;/b&gt;)?= =?UTF-8?Q?=20y=20registro,=20da=20click=20en=20este=20enlace-&gt;=20&lt;b&gt;&lt;a=20?= =?UTF-8?Q?href=3D{1}&gt;Confirmar&lt;/a&gt;&lt;/h&gt;?=
Reply-To: &lt;antonio.dzul@doinmobiliaria.com&gt;
User-Agent: CodeIgniter
X-Sender: antonio.dzul@doinmobiliaria.com
X-Mailer: CodeIgniter
X-Priority: 3 (Normal)
Message-ID: &lt;6358b7ae964283.04165561@doinmobiliaria.com&gt;
Mime-Version: 1.0

</pre>
ERROR - 2022-10-25 22:30:10 --> Email: sendWithSmtp throwed ErrorException: fsockopen(): php_network_getaddresses: getaddrinfo for www.doinmobiliaria.comm failed: Host desconocido.  in C:\xampp\htdocs\pulpox11\system\Email\Email.php:1863
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'fsockopen(): ph...', 'C:\\xampp\\htdocs...', 1863)
#1 C:\xampp\htdocs\pulpox11\system\Email\Email.php(1863): fsockopen('tls://www.doinm...', 465, NULL, NULL, 60)
#2 C:\xampp\htdocs\pulpox11\system\Email\Email.php(1777): CodeIgniter\Email\Email->SMTPConnect()
#3 C:\xampp\htdocs\pulpox11\system\Email\Email.php(1662): CodeIgniter\Email\Email->sendWithSmtp()
#4 C:\xampp\htdocs\pulpox11\system\Email\Email.php(1560): CodeIgniter\Email\Email->spoolEmail()
#5 C:\xampp\htdocs\pulpox11\app\Controllers\API\v1\Usuarios.php(85): CodeIgniter\Email\Email->send()
#6 C:\xampp\htdocs\pulpox11\system\CodeIgniter.php(902): App\Controllers\API\v1\Usuarios->registro()
#7 C:\xampp\htdocs\pulpox11\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\v1\Usuarios))
#8 C:\xampp\htdocs\pulpox11\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\pulpox11\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2022-10-25 22:30:10 --> Email: Unable to send email using SMTP. Your server might not be configured to send mail using this method.
ERROR - 2022-10-25 22:30:10 --> 
ERROR - 2022-10-25 22:30:10 --> c.dzul@hotmail.com - Unable to send email using SMTP. Your server might not be configured to send mail using this method.<br /><pre>Date: Tue, 25 Oct 2022 22:30:10 -0600
From: &quot;Pulpox&quot; &lt;antonio.dzul@doinmobiliaria.com&gt;
Return-Path: &lt;antonio.dzul@doinmobiliaria.com&gt;
To: c.dzul@hotmail.com
Subject: =?UTF-8?Q?Para=20confirmar=20tu=20correo=20(&lt;b&gt;c.dzul@hotmail.com&lt;/b&gt;)?= =?UTF-8?Q?=20y=20registro,=20da=20click=20en=20este=20enlace-&gt;=20&lt;b&gt;&lt;a=20?= =?UTF-8?Q?href=3D{1}&gt;Confirmar&lt;/a&gt;&lt;/h&gt;?=
Reply-To: &lt;antonio.dzul@doinmobiliaria.com&gt;
User-Agent: CodeIgniter
X-Sender: antonio.dzul@doinmobiliaria.com
X-Mailer: CodeIgniter
X-Priority: 3 (Normal)
Message-ID: &lt;6358b7d24c14f1.12930891@doinmobiliaria.com&gt;
Mime-Version: 1.0

</pre>
ERROR - 2022-10-25 22:30:41 --> Email: sendWithSmtp throwed ErrorException: fsockopen(): php_network_getaddresses: getaddrinfo for www.doinmobiliaria.comm failed: Host desconocido.  in C:\xampp\htdocs\pulpox11\system\Email\Email.php:1863
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'fsockopen(): ph...', 'C:\\xampp\\htdocs...', 1863)
#1 C:\xampp\htdocs\pulpox11\system\Email\Email.php(1863): fsockopen('tls://www.doinm...', 465, NULL, NULL, 60)
#2 C:\xampp\htdocs\pulpox11\system\Email\Email.php(1777): CodeIgniter\Email\Email->SMTPConnect()
#3 C:\xampp\htdocs\pulpox11\system\Email\Email.php(1662): CodeIgniter\Email\Email->sendWithSmtp()
#4 C:\xampp\htdocs\pulpox11\system\Email\Email.php(1560): CodeIgniter\Email\Email->spoolEmail()
#5 C:\xampp\htdocs\pulpox11\app\Controllers\API\v1\Usuarios.php(85): CodeIgniter\Email\Email->send()
#6 C:\xampp\htdocs\pulpox11\system\CodeIgniter.php(902): App\Controllers\API\v1\Usuarios->registro()
#7 C:\xampp\htdocs\pulpox11\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\v1\Usuarios))
#8 C:\xampp\htdocs\pulpox11\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\pulpox11\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2022-10-25 22:30:41 --> Email: Unable to send email using SMTP. Your server might not be configured to send mail using this method.
ERROR - 2022-10-25 22:30:41 --> 
ERROR - 2022-10-25 22:30:41 --> c.dzul@hotmail.com - Unable to send email using SMTP. Your server might not be configured to send mail using this method.<br /><pre>Date: Tue, 25 Oct 2022 22:30:41 -0600
From: &quot;Pulpox&quot; &lt;antonio.dzul@doinmobiliaria.com&gt;
Return-Path: &lt;antonio.dzul@doinmobiliaria.com&gt;
To: c.dzul@hotmail.com
Reply-To: &lt;antonio.dzul@doinmobiliaria.com&gt;
User-Agent: CodeIgniter
X-Sender: antonio.dzul@doinmobiliaria.com
X-Mailer: CodeIgniter
X-Priority: 3 (Normal)
Message-ID: &lt;6358b7f1851516.04041227@doinmobiliaria.com&gt;
Mime-Version: 1.0

</pre>
ERROR - 2022-10-25 22:32:29 --> Email: sendWithSmtp throwed ErrorException: fsockopen(): php_network_getaddresses: getaddrinfo for www.doinmobiliaria.comm failed: Host desconocido.  in C:\xampp\htdocs\pulpox11\system\Email\Email.php:1863
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'fsockopen(): ph...', 'C:\\xampp\\htdocs...', 1863)
#1 C:\xampp\htdocs\pulpox11\system\Email\Email.php(1863): fsockopen('tls://www.doinm...', 465, NULL, NULL, 60)
#2 C:\xampp\htdocs\pulpox11\system\Email\Email.php(1777): CodeIgniter\Email\Email->SMTPConnect()
#3 C:\xampp\htdocs\pulpox11\system\Email\Email.php(1662): CodeIgniter\Email\Email->sendWithSmtp()
#4 C:\xampp\htdocs\pulpox11\system\Email\Email.php(1560): CodeIgniter\Email\Email->spoolEmail()
#5 C:\xampp\htdocs\pulpox11\app\Controllers\API\v1\Usuarios.php(85): CodeIgniter\Email\Email->send()
#6 C:\xampp\htdocs\pulpox11\system\CodeIgniter.php(902): App\Controllers\API\v1\Usuarios->registro()
#7 C:\xampp\htdocs\pulpox11\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\v1\Usuarios))
#8 C:\xampp\htdocs\pulpox11\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\pulpox11\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2022-10-25 22:32:29 --> Email: Unable to send email using SMTP. Your server might not be configured to send mail using this method.
ERROR - 2022-10-25 22:32:29 --> 
ERROR - 2022-10-25 22:32:29 --> c.dzul@hotmail.com - Unable to send email using SMTP. Your server might not be configured to send mail using this method.<br /><pre>Date: Tue, 25 Oct 2022 22:32:29 -0600
From: &quot;Pulpox&quot; &lt;antonio.dzul@doinmobiliaria.com&gt;
Return-Path: &lt;antonio.dzul@doinmobiliaria.com&gt;
To: c.dzul@hotmail.com
Subject: =?UTF-8?Q?Registro=20Pulpox?=
Reply-To: &lt;antonio.dzul@doinmobiliaria.com&gt;
User-Agent: CodeIgniter
X-Sender: antonio.dzul@doinmobiliaria.com
X-Mailer: CodeIgniter
X-Priority: 3 (Normal)
Message-ID: &lt;6358b85d5a30b0.87689999@doinmobiliaria.com&gt;
Mime-Version: 1.0

</pre>
ERROR - 2022-10-25 22:34:14 --> Email: sendWithSmtp throwed ErrorException: fsockopen(): php_network_getaddresses: getaddrinfo for www.doinmobiliaria.comm failed: Host desconocido.  in C:\xampp\htdocs\pulpox11\system\Email\Email.php:1863
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'fsockopen(): ph...', 'C:\\xampp\\htdocs...', 1863)
#1 C:\xampp\htdocs\pulpox11\system\Email\Email.php(1863): fsockopen('tls://www.doinm...', 465, NULL, NULL, 60)
#2 C:\xampp\htdocs\pulpox11\system\Email\Email.php(1777): CodeIgniter\Email\Email->SMTPConnect()
#3 C:\xampp\htdocs\pulpox11\system\Email\Email.php(1662): CodeIgniter\Email\Email->sendWithSmtp()
#4 C:\xampp\htdocs\pulpox11\system\Email\Email.php(1560): CodeIgniter\Email\Email->spoolEmail()
#5 C:\xampp\htdocs\pulpox11\app\Controllers\API\v1\Usuarios.php(85): CodeIgniter\Email\Email->send()
#6 C:\xampp\htdocs\pulpox11\system\CodeIgniter.php(902): App\Controllers\API\v1\Usuarios->registro()
#7 C:\xampp\htdocs\pulpox11\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\v1\Usuarios))
#8 C:\xampp\htdocs\pulpox11\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\pulpox11\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2022-10-25 22:34:14 --> Email: Unable to send email using SMTP. Your server might not be configured to send mail using this method.
ERROR - 2022-10-25 22:34:14 --> 
ERROR - 2022-10-25 22:34:14 --> c.dzul@hotmail.com - Unable to send email using SMTP. Your server might not be configured to send mail using this method.<br /><pre>Date: Tue, 25 Oct 2022 22:34:14 -0600
From: &quot;Pulpox&quot; &lt;antonio.dzul@doinmobiliaria.com&gt;
Return-Path: &lt;antonio.dzul@doinmobiliaria.com&gt;
To: c.dzul@hotmail.com
Subject: =?UTF-8?Q?Registro=20Pulpox?=
Reply-To: &lt;antonio.dzul@doinmobiliaria.com&gt;
User-Agent: CodeIgniter
X-Sender: antonio.dzul@doinmobiliaria.com
X-Mailer: CodeIgniter
X-Priority: 3 (Normal)
Message-ID: &lt;6358b8c6307114.49773721@doinmobiliaria.com&gt;
Mime-Version: 1.0

</pre>
ERROR - 2022-10-25 22:38:16 --> Email: sendWithSmtp throwed ErrorException: fsockopen(): php_network_getaddresses: getaddrinfo for www.doinmobiliaria.comm failed: Host desconocido.  in C:\xampp\htdocs\pulpox11\system\Email\Email.php:1863
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'fsockopen(): ph...', 'C:\\xampp\\htdocs...', 1863)
#1 C:\xampp\htdocs\pulpox11\system\Email\Email.php(1863): fsockopen('tls://www.doinm...', 465, NULL, NULL, 60)
#2 C:\xampp\htdocs\pulpox11\system\Email\Email.php(1777): CodeIgniter\Email\Email->SMTPConnect()
#3 C:\xampp\htdocs\pulpox11\system\Email\Email.php(1662): CodeIgniter\Email\Email->sendWithSmtp()
#4 C:\xampp\htdocs\pulpox11\system\Email\Email.php(1560): CodeIgniter\Email\Email->spoolEmail()
#5 C:\xampp\htdocs\pulpox11\app\Controllers\API\v1\Usuarios.php(85): CodeIgniter\Email\Email->send()
#6 C:\xampp\htdocs\pulpox11\system\CodeIgniter.php(902): App\Controllers\API\v1\Usuarios->registro()
#7 C:\xampp\htdocs\pulpox11\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\v1\Usuarios))
#8 C:\xampp\htdocs\pulpox11\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\pulpox11\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2022-10-25 22:38:16 --> Email: Unable to send email using SMTP. Your server might not be configured to send mail using this method.
ERROR - 2022-10-25 22:38:16 --> 
ERROR - 2022-10-25 22:38:16 --> c.dzul@hotmail.com - Unable to send email using SMTP. Your server might not be configured to send mail using this method.<br /><pre>Date: Tue, 25 Oct 2022 22:38:16 -0600
From: &quot;Pulpox&quot; &lt;antonio.dzul@doinmobiliaria.com&gt;
Return-Path: &lt;antonio.dzul@doinmobiliaria.com&gt;
To: c.dzul@hotmail.com
Subject: =?UTF-8?Q?Registro=20Pulpox?=
Reply-To: &lt;antonio.dzul@doinmobiliaria.com&gt;
User-Agent: CodeIgniter
X-Sender: antonio.dzul@doinmobiliaria.com
X-Mailer: CodeIgniter
X-Priority: 3 (Normal)
Message-ID: &lt;6358b9b8e32342.59426039@doinmobiliaria.com&gt;
Mime-Version: 1.0

</pre>
ERROR - 2022-10-25 22:41:27 --> Email: sendWithSmtp throwed ErrorException: fsockopen(): php_network_getaddresses: getaddrinfo for www.doinmobiliaria.comm failed: Host desconocido.  in C:\xampp\htdocs\pulpox11\system\Email\Email.php:1863
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'fsockopen(): ph...', 'C:\\xampp\\htdocs...', 1863)
#1 C:\xampp\htdocs\pulpox11\system\Email\Email.php(1863): fsockopen('tls://www.doinm...', 465, NULL, NULL, 60)
#2 C:\xampp\htdocs\pulpox11\system\Email\Email.php(1777): CodeIgniter\Email\Email->SMTPConnect()
#3 C:\xampp\htdocs\pulpox11\system\Email\Email.php(1662): CodeIgniter\Email\Email->sendWithSmtp()
#4 C:\xampp\htdocs\pulpox11\system\Email\Email.php(1560): CodeIgniter\Email\Email->spoolEmail()
#5 C:\xampp\htdocs\pulpox11\app\Controllers\API\v1\Usuarios.php(85): CodeIgniter\Email\Email->send()
#6 C:\xampp\htdocs\pulpox11\system\CodeIgniter.php(902): App\Controllers\API\v1\Usuarios->registro()
#7 C:\xampp\htdocs\pulpox11\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\v1\Usuarios))
#8 C:\xampp\htdocs\pulpox11\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\pulpox11\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2022-10-25 22:41:27 --> Email: Unable to send email using SMTP. Your server might not be configured to send mail using this method.
ERROR - 2022-10-25 22:41:27 --> 
ERROR - 2022-10-25 22:41:27 --> c.dzul@hotmail.com - Unable to send email using SMTP. Your server might not be configured to send mail using this method.<br /><pre>Date: Tue, 25 Oct 2022 22:41:27 -0600
From: &quot;Pulpox&quot; &lt;antonio.dzul@doinmobiliaria.com&gt;
Return-Path: &lt;antonio.dzul@doinmobiliaria.com&gt;
To: c.dzul@hotmail.com
Subject: =?UTF-8?Q?Registro=20Pulpox?=
Reply-To: &lt;antonio.dzul@doinmobiliaria.com&gt;
User-Agent: CodeIgniter
X-Sender: antonio.dzul@doinmobiliaria.com
X-Mailer: CodeIgniter
X-Priority: 3 (Normal)
Message-ID: &lt;6358ba770ea013.32740061@doinmobiliaria.com&gt;
Mime-Version: 1.0

</pre>
CRITICAL - 2022-10-25 22:50:42 --> There is no data to update.
in SYSTEMPATH\BaseModel.php on line 866.
 1 SYSTEMPATH\BaseModel.php(866): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
 2 SYSTEMPATH\Model.php(693): CodeIgniter\BaseModel->update(true, [])
 3 APPPATH\Controllers\API\v1\Usuarios.php(90): CodeIgniter\Model->update(true, [...])
 4 SYSTEMPATH\CodeIgniter.php(902): App\Controllers\API\v1\Usuarios->registro()
 5 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\v1\Usuarios))
 6 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-10-25 22:51:33 --> There is no data to update.
in SYSTEMPATH\BaseModel.php on line 866.
 1 SYSTEMPATH\BaseModel.php(866): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
 2 SYSTEMPATH\Model.php(693): CodeIgniter\BaseModel->update(true, [])
 3 APPPATH\Controllers\API\v1\Usuarios.php(91): CodeIgniter\Model->update(true, [...])
 4 SYSTEMPATH\CodeIgniter.php(902): App\Controllers\API\v1\Usuarios->registro()
 5 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\v1\Usuarios))
 6 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-10-25 22:52:17 --> There is no data to update.
in SYSTEMPATH\BaseModel.php on line 866.
 1 SYSTEMPATH\BaseModel.php(866): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
 2 SYSTEMPATH\Model.php(693): CodeIgniter\BaseModel->update(true, [])
 3 APPPATH\Controllers\API\v1\Usuarios.php(91): CodeIgniter\Model->update(true, [...])
 4 SYSTEMPATH\CodeIgniter.php(902): App\Controllers\API\v1\Usuarios->registro()
 5 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\v1\Usuarios))
 6 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-10-25 22:54:01 --> There is no data to update.
in SYSTEMPATH\BaseModel.php on line 866.
 1 SYSTEMPATH\BaseModel.php(866): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
 2 SYSTEMPATH\Model.php(693): CodeIgniter\BaseModel->update(true, [])
 3 APPPATH\Controllers\API\v1\Usuarios.php(91): CodeIgniter\Model->update(true, [...])
 4 SYSTEMPATH\CodeIgniter.php(902): App\Controllers\API\v1\Usuarios->registro()
 5 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\v1\Usuarios))
 6 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-10-25 22:55:41 --> Undefined variable $data2
in APPPATH\Controllers\API\v1\Usuarios.php on line 91.
 1 APPPATH\Controllers\API\v1\Usuarios.php(91): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $data2', 'APPPATH\\Controllers\\API\\v1\\Usuarios.php', 91)
 2 SYSTEMPATH\CodeIgniter.php(902): App\Controllers\API\v1\Usuarios->registro()
 3 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\v1\Usuarios))
 4 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-10-25 22:56:21 --> There is no data to update.
in SYSTEMPATH\BaseModel.php on line 866.
 1 SYSTEMPATH\BaseModel.php(866): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
 2 SYSTEMPATH\Model.php(693): CodeIgniter\BaseModel->update(true, [])
 3 APPPATH\Controllers\API\v1\Usuarios.php(91): CodeIgniter\Model->update(true, [...])
 4 SYSTEMPATH\CodeIgniter.php(902): App\Controllers\API\v1\Usuarios->registro()
 5 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\v1\Usuarios))
 6 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-10-25 22:57:21 --> whereIn() expects $values to be of type array or closure
in SYSTEMPATH\Database\BaseBuilder.php on line 907.
 1 SYSTEMPATH\Database\BaseBuilder.php(789): CodeIgniter\Database\BaseBuilder->_whereIn('usuarios_preregistro.usupr_id', true, false, 'AND ', null)
 2 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->whereIn('usuarios_preregistro.usupr_id', true)
 3 SYSTEMPATH\BaseModel.php(885): CodeIgniter\Model->doUpdate(true, [...])
 4 SYSTEMPATH\Model.php(693): CodeIgniter\BaseModel->update(true, [...])
 5 APPPATH\Controllers\API\v1\Usuarios.php(91): CodeIgniter\Model->update(true, [...])
 6 SYSTEMPATH\CodeIgniter.php(902): App\Controllers\API\v1\Usuarios->registro()
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\v1\Usuarios))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-10-25 22:57:57 --> whereIn() expects $values to be of type array or closure
in SYSTEMPATH\Database\BaseBuilder.php on line 907.
 1 SYSTEMPATH\Database\BaseBuilder.php(789): CodeIgniter\Database\BaseBuilder->_whereIn('usuarios_preregistro.usupr_id', true, false, 'AND ', null)
 2 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->whereIn('usuarios_preregistro.usupr_id', true)
 3 SYSTEMPATH\BaseModel.php(885): CodeIgniter\Model->doUpdate(true, [...])
 4 SYSTEMPATH\Model.php(693): CodeIgniter\BaseModel->update(true, [...])
 5 APPPATH\Controllers\API\v1\Usuarios.php(91): CodeIgniter\Model->update(true, [...])
 6 SYSTEMPATH\CodeIgniter.php(902): App\Controllers\API\v1\Usuarios->registro()
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\v1\Usuarios))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-10-25 22:58:37 --> whereIn() expects $values to be of type array or closure
in SYSTEMPATH\Database\BaseBuilder.php on line 907.
 1 SYSTEMPATH\Database\BaseBuilder.php(789): CodeIgniter\Database\BaseBuilder->_whereIn('usuarios_preregistro.usupr_id', true, false, 'AND ', null)
 2 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->whereIn('usuarios_preregistro.usupr_id', true)
 3 SYSTEMPATH\BaseModel.php(885): CodeIgniter\Model->doUpdate(true, [...])
 4 SYSTEMPATH\Model.php(693): CodeIgniter\BaseModel->update(true, [...])
 5 APPPATH\Controllers\API\v1\Usuarios.php(91): CodeIgniter\Model->update(true, [...])
 6 SYSTEMPATH\CodeIgniter.php(902): App\Controllers\API\v1\Usuarios->registro()
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\v1\Usuarios))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-10-25 22:59:59 --> whereIn() expects $values to be of type array or closure
in SYSTEMPATH\Database\BaseBuilder.php on line 907.
 1 SYSTEMPATH\Database\BaseBuilder.php(789): CodeIgniter\Database\BaseBuilder->_whereIn('usuarios_preregistro.usupr_id', true, false, 'AND ', null)
 2 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->whereIn('usuarios_preregistro.usupr_id', true)
 3 SYSTEMPATH\BaseModel.php(885): CodeIgniter\Model->doUpdate(true, [...])
 4 SYSTEMPATH\Model.php(693): CodeIgniter\BaseModel->update(true, [...])
 5 APPPATH\Controllers\API\v1\Usuarios.php(91): CodeIgniter\Model->update(true, [...])
 6 SYSTEMPATH\CodeIgniter.php(902): App\Controllers\API\v1\Usuarios->registro()
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\v1\Usuarios))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-10-25 23:01:03 --> whereIn() expects $values to be of type array or closure
in SYSTEMPATH\Database\BaseBuilder.php on line 907.
 1 SYSTEMPATH\Database\BaseBuilder.php(789): CodeIgniter\Database\BaseBuilder->_whereIn('usuarios_preregistro.usupr_id', true, false, 'AND ', null)
 2 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->whereIn('usuarios_preregistro.usupr_id', true)
 3 SYSTEMPATH\BaseModel.php(885): CodeIgniter\Model->doUpdate(true, [...])
 4 SYSTEMPATH\Model.php(693): CodeIgniter\BaseModel->update(true, [...])
 5 APPPATH\Controllers\API\v1\Usuarios.php(91): CodeIgniter\Model->update(true, [...])
 6 SYSTEMPATH\CodeIgniter.php(902): App\Controllers\API\v1\Usuarios->registro()
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\v1\Usuarios))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-10-25 23:02:42 --> whereIn() expects $values to be of type array or closure
in SYSTEMPATH\Database\BaseBuilder.php on line 907.
 1 SYSTEMPATH\Database\BaseBuilder.php(789): CodeIgniter\Database\BaseBuilder->_whereIn('usuarios_preregistro.usupr_id', true, false, 'AND ', null)
 2 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->whereIn('usuarios_preregistro.usupr_id', true)
 3 SYSTEMPATH\BaseModel.php(885): CodeIgniter\Model->doUpdate(true, [...])
 4 SYSTEMPATH\Model.php(693): CodeIgniter\BaseModel->update(true, [...])
 5 APPPATH\Controllers\API\v1\Usuarios.php(91): CodeIgniter\Model->update(true, [...])
 6 SYSTEMPATH\CodeIgniter.php(902): App\Controllers\API\v1\Usuarios->registro()
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\v1\Usuarios))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-10-25 23:03:05 --> whereIn() expects $values to be of type array or closure
in SYSTEMPATH\Database\BaseBuilder.php on line 907.
 1 SYSTEMPATH\Database\BaseBuilder.php(789): CodeIgniter\Database\BaseBuilder->_whereIn('usuarios_preregistro.usupr_id', true, false, 'AND ', null)
 2 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->whereIn('usuarios_preregistro.usupr_id', true)
 3 SYSTEMPATH\BaseModel.php(885): CodeIgniter\Model->doUpdate(true, [...])
 4 SYSTEMPATH\Model.php(693): CodeIgniter\BaseModel->update(true, [...])
 5 APPPATH\Controllers\API\v1\Usuarios.php(91): CodeIgniter\Model->update(true, [...])
 6 SYSTEMPATH\CodeIgniter.php(902): App\Controllers\API\v1\Usuarios->registro()
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\v1\Usuarios))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-10-25 23:03:21 --> whereIn() expects $values to be of type array or closure
in SYSTEMPATH\Database\BaseBuilder.php on line 907.
 1 SYSTEMPATH\Database\BaseBuilder.php(789): CodeIgniter\Database\BaseBuilder->_whereIn('usuarios_preregistro.usupr_id', true, false, 'AND ', null)
 2 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->whereIn('usuarios_preregistro.usupr_id', true)
 3 SYSTEMPATH\BaseModel.php(885): CodeIgniter\Model->doUpdate(true, [...])
 4 SYSTEMPATH\Model.php(693): CodeIgniter\BaseModel->update(true, [...])
 5 APPPATH\Controllers\API\v1\Usuarios.php(91): CodeIgniter\Model->update(true, [...])
 6 SYSTEMPATH\CodeIgniter.php(902): App\Controllers\API\v1\Usuarios->registro()
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\v1\Usuarios))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2022-10-25 23:07:20 --> Email: sendWithSmtp throwed ErrorException: fsockopen(): php_network_getaddresses: getaddrinfo for www.doinmobiliaria.comm failed: Host desconocido.  in C:\xampp\htdocs\pulpox11\system\Email\Email.php:1863
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'fsockopen(): ph...', 'C:\\xampp\\htdocs...', 1863)
#1 C:\xampp\htdocs\pulpox11\system\Email\Email.php(1863): fsockopen('tls://www.doinm...', 465, NULL, NULL, 60)
#2 C:\xampp\htdocs\pulpox11\system\Email\Email.php(1777): CodeIgniter\Email\Email->SMTPConnect()
#3 C:\xampp\htdocs\pulpox11\system\Email\Email.php(1662): CodeIgniter\Email\Email->sendWithSmtp()
#4 C:\xampp\htdocs\pulpox11\system\Email\Email.php(1560): CodeIgniter\Email\Email->spoolEmail()
#5 C:\xampp\htdocs\pulpox11\app\Controllers\API\v1\Usuarios.php(85): CodeIgniter\Email\Email->send()
#6 C:\xampp\htdocs\pulpox11\system\CodeIgniter.php(902): App\Controllers\API\v1\Usuarios->registro()
#7 C:\xampp\htdocs\pulpox11\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\v1\Usuarios))
#8 C:\xampp\htdocs\pulpox11\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\pulpox11\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2022-10-25 23:07:20 --> Email: Unable to send email using SMTP. Your server might not be configured to send mail using this method.
ERROR - 2022-10-25 23:07:20 --> 
ERROR - 2022-10-25 23:07:20 --> c.dzul@hotmail.com - Unable to send email using SMTP. Your server might not be configured to send mail using this method.<br /><pre>Date: Tue, 25 Oct 2022 23:07:20 -0600
From: &quot;Pulpox&quot; &lt;antonio.dzul@doinmobiliaria.com&gt;
Return-Path: &lt;antonio.dzul@doinmobiliaria.com&gt;
To: c.dzul@hotmail.com
Subject: =?UTF-8?Q?Registro=20Pulpox?=
Reply-To: &lt;antonio.dzul@doinmobiliaria.com&gt;
User-Agent: CodeIgniter
X-Sender: antonio.dzul@doinmobiliaria.com
X-Mailer: CodeIgniter
X-Priority: 3 (Normal)
Message-ID: &lt;6358c088a3ed30.81215434@doinmobiliaria.com&gt;
Mime-Version: 1.0

</pre>
